x-wordpress: &base-wordpress
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    volumes:
      - './wordpress:/var/www/html:z'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    profiles:
      - prod
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    volumes:
      - './nginx/conf/:/etc/nginx/conf.d/:ro'
      - './certbot/www:/var/www/certbot/:ro'
      - './certbot/ssl/:/etc/nginx/ssl/:ro'

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    profiles:
      - prod
    volumes:
      - './certbot/www/:/var/www/certbot/:rw'
      - './certbot/ssl/:/etc/letsencrypt/:rw'

  dev-wordpress:
    <<: *base-wordpress
    ports:
      - '8080:80'
    profiles:
      - dev

  setup-wordpress:
    <<: *base-wordpress
    ports:
      - '80:80'
    profiles:
      - setup

  wordpress:
    <<: *base-wordpress
    profiles:
      - prod

  db:
    container_name: db
    image: mariadb:lts-noble
    volumes:
      - './.db/data:/var/lib/mysql'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  php_myadmin:
    container_name: php_myadmin
    image: phpmyadmin:latest
    profiles:
      - dev
      - debug
    restart: unless-stopped
    ports:
      - '8081:80'
    environment:
      PMA_HOSTS: db
      MYSQL_ROOT_PASSWORD: root